### ISSUE TITLE
Can you provide a static example for quick testing

### ISSUE THREAD

**Issue by Schizo** [jazzband/django-embed-video#106]
I wanted to check this project out, but I would like to see a static example to see how it works. 

```
{% video item.video as my_video %}
URL: { "https://vimeo.com/9011932" }
Thumbnail: { "https://i.vimeocdn.com/video/43561837_100x75.webp" }
Backend: {{ my_video.backend }
{% video my_video 'small' %}
{% endvideo %}
```

Am I missing something here ? 

Thanks

**Comment by aleksihakli** [comment]
Are you saying that the example above does not work or that it should be available in the docs straight away? 

The code should use double `{{ braces }}` in the template by the way.

**Comment by aleksihakli** [comment]
You can find examples in the example projects and tests. Please make sure you have checked out the documentation and have the application in `INSTALLED_APPS` :)
