### ISSUE TITLE
Support AMP pages

### ISSUE THREAD

**Issue by Letme** [jazzband/django-embed-video#121]
I think nowdays with the traction of the AMP, we could get the video tag to support AMP style of formatting? There is `amp-youtube` tag https://amp.dev/documentation/components/amp-youtube/ and also `amp-vimeo`.

I will be soon migrating html site to amp and i used django-embed-video, so I would like to just add a setting somewhere and let the plugin generate corresponding code.

**Comment by aleksihakli** [comment]
The project is always open for PRs. A new template tag would probably be the cleanest approach for implementing this, something like `{amp_video video}`
