### ISSUE TITLE
Can't get django-embed-video to work on the frontend

### ISSUE THREAD

**Issue by ghost-goblin** [jazzband/django-embed-video#125]
I am trying to use django-embed-video to make posts.
I have followed the docs.
Everything is working fine on the admin page but I cant get the code to work on the template.
`{% extends "blog/base.html" %}
{% load embed_video_tags %}
{% video post.video 'small' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
                {% if videos %}
                {% for v in videos %}
                {{ post.video }}
                {% endfor %}
                {% else %}
                <p>No videos yet</p>
                {% endif %}
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}`

**Comment by StephenAM1** [comment]
Hey ghost-goblin is there a reason you closed this? I've been struggling with getting my template tag to work. I can embed a video within admin, but I can't get it to pull through to the front-end and I really have no idea why. I've seen the issue brought up a few times on here but can't seem to find a concrete solution. If you figured something out that would be great if you could share.

**Comment by ghost-goblin** [comment]
Hey Stephen,

Yes I managed to figure it out by putting the code in an iframe:
```
{% load embed_video_tags %}
{% video post.video as video %}
<iframe width="420" height="345" src="{{ video.url }}"></iframe>
{% endvideo %}
```
Let me know if this works :)

**Comment by StephenAM1** [comment]
Thanks for the reply :) I am still getting a UnknownBackendException, unfortunately. It just can't seem to find the instance I created in admin, I am sure I just mapped something wrong. I will keep digging, appreciate the help!

**Comment by StephenAM1** [comment]
Hey ghost-goblin, just got this to work using your code with the iframe. Thanks again for the help.
