### ISSUE TITLE
Emails to @mgrdcm not deliverable

### ISSUE THREAD

**Issue by jezdez** [jazzband/django-embed-video#129]
Hey @mgrdcm, as a project lead we need to be able to reach you via email and the email address that the Jazzband site has fetched from the GitHub API is defunct according our email provider. Please reach out to me about this so you can receive email notifications again.

I've temporarily disabled your project lead permissions to mitigate a possible domain take over.

@aleksihakli FYI ^

**Comment by aleksihakli** [comment]
@jezdez thanks for letting me know as well! I'll try and handle releases in the meanwhile.

**Comment by mgrdcm** [comment]
Hey @jezdez!  Sorry, my colo'd server had some hardware problems.  I've fixed my profile.

**Comment by jezdez** [comment]
@mgrdcm Hey there, thank you for updating your GitHub profile, sadly that's not enough for this to work since we're actually fetching the email addresses from your GitHub user info, so basically the actual email addresses that you added to GitHub and verified. Could you double-check if a working email address is listed on your https://github.com/settings/emails?

Alternatively, it would help if you would re-login on https://jazzband.co/ to sync your profile info again. Thanks again for your help in this matter!

**Comment by mgrdcm** [comment]
@jezdez  Done!  It was showing as pending authorization so that link must have broken at some point.  How does it look now?

**Comment by jezdez** [comment]
@mgrdcm That did the trick, thank you! I've reinstated you as project lead. If you don't mind, I'll leave @aleksihakli as a backup. Cheers!

**Comment by mgrdcm** [comment]
Oh absolutely @jezdez the more the merrier.  Actually since I've had that power I don't think I've even handled a release yet!
