### ISSUE TITLE
django-embed-video attaches "_RvGGQVH" to video 

### ISSUE THREAD

**Issue by dtdibaba** [jazzband/django-embed-video#140]

**Comment by aleksihakli** [comment]
Could we have a bit more description on this?

**Comment by dtdibaba** [comment]
Sorry, I found out the problem was caused by another package not this one. This one works perfectly. I was trying to add media upload button it failed to play the media after uploading.

**Comment by aleksihakli** [comment]
OK, good to know! I'll go ahead and close this issue then. Thanks for checking back with the issue.

**Comment by dtdibaba** [comment]
Yes, you can close it.
