### ISSUE TITLE
Issues with testing on Pypy3

### ISSUE THREAD

**Issue by jezdez** [jazzband/django-embed-video#146]
Seems like something is wrong with the Pypy3 setup: https://github.com/jazzband/django-embed-video/actions/runs/430202855

@aleksihakli Any idea what that could be?

**Comment by aleksihakli** [comment]
Seems like the problem is https://github.com/actions/setup-python/issues/171

I'm wondering if we should just deprecate PyPy3 from the required test matrix, or keep it?

Please also see jazzband/django-embed-video#147

**Comment by jezdez** [comment]
Let's keep it as there seems to be a fix already out.
