### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by pawel-ch** [jazzband/django-embed-video#154]
Hi, would you be interested in PR from last 2 commits from https://github.com/propertygroup/django-embed-video/commits/master? That would be the first translation, so I don't know what convention would be appropriate and how would you like to treat the metadata: remove or fill. And if fill, then in what way?

Of course I can adjust anything before creating PR.

**Comment by aleksihakli** [comment]
Hi @pawel-ch! I think translations and setting them up are always cool, Django itself does it. This would make it easier for future contributors to add any necessary translations as well. Please feel free to open a PR 👍

**Comment by pawel-ch** [comment]
Hi @aleksihakli, I just created the PR. I'm sorry it took so long.

Making more translations is as simple as:
```shell
django-admin makemessages -l pl
# edit django.po
django-admin compilemessages
```

**Comment by aleksihakli** [comment]
Thanks for the PR @pawel-ch! 👍
