### ISSUE TITLE
Adjust project settings to allow merging PRs

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-embed-video#168]
Current project settings seem to require deprecated build checks before merging in e.g. #167

Would it be possible to reconfigure PR checks?

**Comment by jezdez** [comment]
<img width="746" alt="CleanShot 2022-01-11 at 17 34 29@2x" src="https://user-images.githubusercontent.com/1610/148983245-d78e8c2a-529c-48aa-a8c3-6c3c42f288d1.png">

Does this look right?

**Comment by aleksihakli** [comment]
I think that looks good if we want to keep the gates on for status checks, I was able to succesfully merge the PR with Django updates with these settings 👍 Thanks!
