### ISSUE TITLE
Add (Youtube) playlist support

### ISSUE THREAD

**Issue by hop** [jazzband/django-embed-video#169]
I would like to add support for Youtube playlists, if you are interested.

For now I've implemented a separate backend to make fiddling around easier. Which would you prefer: this approach or merging all the logic into the existing backend? The latter seems a bit messy, since playlist IDs are of a different length and given as query parameters.

Related question: the fallback to `urlparse` in https://github.com/jazzband/django-embed-video/blob/f2b134ca19d1c7e9ea532550b3ca15eae126de55/embed_video/backends.py#L323-L326 seems redundand.

What's the reasoning behind this? I myself would prefer the `urlparse` approach in the first place.

**Comment by aleksihakli** [comment]
Hi @hop! Adding a separate implementation for the playlists could be a good first step and then we could see if the single video and playlist support would be easier to support in one or two distinct backends.
