### ISSUE TITLE
example_project outdated

### ISSUE THREAD

**Issue by kakulukia** [jazzband/django-embed-video#175]
I just tried to start the example project and there are multiple issues with that. :(

1. requirements.txt lists Django>=2.2 which is not compatible with the example_project 
2. requirements.txt does not include django-embed-video and fails to start
3. the instructions on how to install the example_project fail to mention how to install the fixtures for posts app and thus you get an empty page
4. 'posts' is not a registered namespace when trying to load the example page

**Comment by aleksihakli** [comment]
Hey @kakulukia and thanks for reporting the issue!

Would you be interested in opening a PR that fixes the aforementioned issues?

**Comment by aleksihakli** [comment]
Fixed by #179
