### ISSUE TITLE
wrong path on installation.rst

### ISSUE THREAD

**Issue by angryfoxx** [jazzband/django-embed-video#185]
The 'request' path on installation.rst is wrong. It's must be 'django.template.context_processors.request'
![installation_rst](https://user-images.githubusercontent.com/88541716/188268090-63b2b75b-d68e-4d9b-a84d-f7e1f7d96b39.png)

**Comment by aleksihakli** [comment]
Thanks for reporting @angryfoxx! Would you be inclined to open a PR for updating the documentation?

**Comment by angryfoxx** [comment]
> Thanks for reporting @angryfoxx! Would you be inclined to open a PR for updating the documentation?

#192

**Comment by angryfoxx** [comment]
fix: installation.rst #192

**Comment by aleksihakli** [comment]
Fixed by the merged MR, thanks @angryfoxx
