### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by yetty** [jazzband/django-embed-video#59]
I don't have time anymore to work on django-embed-video. The package is pretty stable and requires just occasional updates. Anyway, there are still some problems to be solved ([see issues](https://github.com/yetty/django-embed-video/issues)). 

My appeals to new maintainer:
- keep backward compatibility as much as possible
- write unit tests
- give some time to update documentation

If you would like to become a maintainer, I give you all the necessary permissions (github repo, pipy, read the docs etc.)

**Comment by thijstriemstra** [comment]
I guess I would be interested. Sent me an email at info @ collab.nl and we'll go from there?

**Comment by mgrdcm** [comment]
Thanks for your work on this, @yetty!  I'd also be interested in helping maintain this handy package, which has certainly proved useful to me.

**Comment by yetty** [comment]
Great, thank you. I've added you as collaborators to this repository. Please give me your usernames for pipy and read the docs, so I would be able to add you there too.
