### ISSUE TITLE
HTTPS enabled but django admin EmbedVideoField is embedding unsecure HTTP

### ISSUE THREAD

**Issue by chromaticgliss** [jazzband/django-embed-video#70]
It seems in the admin the form still tries to embed an HTTP video even if HTTPS is enabled and the request to page is done via HTTPS. Seems all video backends are doing this. Inspecting values in the `backend.protocol()` showed `allow_https=True` and `is_secure=False` which gets used when generating the url.

When I intercepted the actual request, django's `request.is_secure()` returns True. Seems this should be overriding the default 'False' value somehow.

The request context processor is present as well.

**Comment by SalahAdDin** [comment]
@marcosguedes But, could not this package support this feature?

**Comment by marcosguedes** [comment]
It does, just not by default. Should it?

I guess we're at the stage where https is becoming more widespread and all supplied backends support https so I find it justifiable to change. However the only thing I did was provide a solution for this particular problem.
