### ISSUE TITLE
Template_context_processors has been depreciated in django 1.8

### ISSUE THREAD

**Issue by Basiczombie** [jazzband/django-embed-video#71]
```
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
)
```

This was depreciated in Django 1.8. It is saying that Template Dictionaries take precedent. Do you have a work around to place the needed code within the Templates -> options -> context_processors in the settings post 1.8?

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

**Comment by SalahAdDin** [comment]
Which exactly the problem?

**Comment by Basiczombie** [comment]
The setting TEMPLATE_CONTEXT_PROCESSORS has been depreciated in Django 1.8. It still works but my server keeps yelling at me to put it into the TEMPLATES setting which when added to the context_processors in the Options breaks the module.

**Comment by thijstriemstra** [comment]
how does it break? any error message?

**Comment by SalahAdDin** [comment]
@Basiczombie can you put the warning message here please?

**Comment by Basiczombie** [comment]
WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.

**Comment by SalahAdDin** [comment]
But, doesn't ıt show the exactly fıle and lıne that gıve you the error?

**Comment by CedricCarrard** [comment]
@Basiczombie fixed with new version ?
