### ISSUE TITLE
Broken releases on PyPI

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-embed-video#76]
This project has gone over a number of releases today, breaking our builds. Version `1.1.0` was pulled from PyPI and version `1.1.1` and then `1.1.1` was pulled from PyPI as well and replaced with `1.1.0a0` and `1.1.1a0`.

This breaks our builds and it is pretty annoying to go over and iterate the packages because there is no sano version in PyPI; why do you remove dependencies after adding them?

**Comment by CedricCarrard** [comment]
@aleksihakli We had a problem with Pypi. Thank you for using the version 1.1.2 or 1.1.0. Sorry for the problem.
