### ISSUE TITLE
Don't remove older versions from PyPI

### ISSUE THREAD

**Issue by koterpillar** [jazzband/django-embed-video#78]
When using [pip-tools](https://github.com/jazzband/pip-tools) to pin requirements, you get `django-embed-video==1.1.0` (for example). `1.1.0` appears to have been removed from PyPI. Since `1.1.2` doesn't fix any security vulnerabilities or make `1.1.0` otherwise dangerous to use, it would be beneficial to keep the old versions on PyPI for pinned version builds to stay reproducible.

**Comment by CedricCarrard** [comment]
@koterpillar We had a problem with Pypi. Thank you for using the version 1.1.2. Sorry for the problem.

**Comment by koterpillar** [comment]
Going forward, will `1.1.2` stay on PyPI even when `1.1.3` (say) is released?
