### ISSUE TITLE
Versions 1.1.0 and 1.1.1 have been removed from PyPI.

### ISSUE THREAD

**Issue by silentbugs** [jazzband/django-embed-video#80]
running `pip install django-embed-video==1.1.0` returns:

```
Could not find a version that satisfies the requirement django-embed-video==1.1.0 (from 
versions: 0.0.1, 0.1.0, 0.2.0, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 1.0.0, 
1.1.2) No matching distribution found for django-embed-video==1.1.0
```

Was the removal of those releases intentional? If so, should we consider upgrading from 1.1.0? If not, why were they removed?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by thijstriemstra** [comment]
@SalahAdDin what do you mean?

**Comment by CedricCarrard** [comment]
@silentbugs We had a problem with Pypi. Thank you for using the version 1.1.2 or 1.1.0. Sorry for the problem.
