### ISSUE TITLE
unexpected keyword argument 'renderer' DJANGO 2.1

### ISSUE THREAD

**Issue by FilipeRafaeli** [jazzband/django-embed-video#90]
in django 2.1 an error happens

`

Request Method: | GET
-- | --
http://localhost:8000/admin/videos/youtube/add/
2.1
TypeError
render() got an unexpected keyword argument 'renderer'

`

**Comment by mgrdcm** [comment]
This is addressed in PR #88.

For now you can use the workaround mentioned there.
