### ISSUE TITLE
Example Project not updated for new Django version

### ISSUE THREAD

**Issue by HarryBerry87** [jazzband/django-embed-video#96]
Hello,

 I am very new to Django and Python in general, and I am having an issue running the example_project provided in the repository. Looking through some of the more recent (last 6 months) issues, it seems Django 2.1 update is stopping me from [creating a database ](https://django-embed-video.readthedocs.io/en/v1.2.0/example-project.html#running-example-project). 

I replaced on my machine the `from django.core.urlresolver import reverse` line in posts/models.py with `from django.urls import reverse`, but something involving the urls is stopping it. If someone smarter could recreate it they could probably explain the problem better. Thanks, cheers!

**Comment by GregKaleka** [comment]
Here are the minimum changes needed to get the example project to work on Django 2.x:

1. Change the `reverse` import as you mention in posts/models.py
2. Change the admin.site.urls line in example_project/urls.py to read `url(r'^admin/', admin.site.urls),`
3. Add the line `app_name = "posts"` to posts/urls.py on line 5
4. After running `migrate`, you also need to run `python manage.py loaddata initial_data` to load the provided fixtures into the database

**Comment by aleksihakli** [comment]
The docs should be updated for multiple other settings as well as they refer to old Django configuration flags and types.

**Comment by Nilansha** [comment]
1. changed (example_project -> posts -> models.py) this `from django.core.urlresolver import reverse`  to `from django.urls import reverse`
2. changed (example_project -> urls.py)
 `url(r'^admin/', include(admin.site.urls)),` to `url(r'^admin/', admin.site.urls),`
and
`url(r'^', include('posts.urls', namespace='posts')),` to `url(r'^', include('posts.urls'), name='posts'),`

Then it works fine :)

**Comment by aleksihakli** [comment]
@Nilansha would you like to make a PR so we can update the upstream code?

**Comment by Nilansha** [comment]
I don't have permission to make PR for you repo

**Comment by aleksihakli** [comment]
@Nilansha permissions aren't the problem on GitHub. You can make a fork, which creates a repository under your account, and then make the changes. When you go to the repository on GitHun and go to pull requests view you can just open a PR and it will show here. We can then merge it with one click. I hope this helps!

**Comment by Nilansha** [comment]
Great. Thanks a lot for your guidance this is my first contribution and the PR.

**Comment by aleksihakli** [comment]
It's great to help people getting started! The changes look good in the fork you have made, but I can't see the PR under this repository yet. GitHub has a [decent document describing PRs from forks](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

**Comment by Nilansha** [comment]
Thanks. Done. It should ok this time.

**Comment by aleksihakli** [comment]
PR merged. Thank you for the contribution @Nilansha!
