### ISSUE TITLE
100% x 100% width / height

### ISSUE THREAD

**Issue by NomeChomsky** [jazzband/django-embed-video#98]
When I put {% video my_video "100% x 100%" %} into template tag, I can get 100% width, but I can't ever get 100% height. I always just get a fraction of the height, usually about 10%. I've tried putting it into a div with 100% height also, but this doesn't seem to work?

![image](https://user-images.githubusercontent.com/46587871/55929998-e453c880-5c3c-11e9-9024-89e9f3eb899a.png)

**Comment by adriancarayol** [comment]
You need to set a height in pixels in the parent container, for example:

```
.video {
height: 400px;
}
<div class="video">
{% video my_video "100% x 100%" %}
</div>
```
